/*= ProjectConfiguration.h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationDevApp_h
#define ProjectConfigurationDevApp_h

	#define MULTIPUNTAMENTO
	#define OMVLICENSE @"openpaybankplugin-sci-demoapp-dev-ios"

#endif /* ProjectConfigurationDevApp_h*/