/*= ProjectConfiguration.h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationDevApp_h
#define ProjectConfigurationDevApp_h

	#undef MULTIPUNTAMENTO
	#define OMVLICENSE @"openpaybankplugin-sci-demoapp-github-ios"

#endif /* ProjectConfigurationDevApp_h*/